steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/banded-object-438816-p9
/kamal-100990948/image:${COMMIT_SHA}', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/banded-object-438816-p9
/kamal-100990948/image:${COMMIT_SHA}']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
